# Generated by Django 6.0.7 on 2026-07-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_created_at_conversation_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
