# Generated by Django 6.0.7 on 2026-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'ارسال شده'), ('graded', 'نمره\u200cدهی شده'), ('late', 'دیر ارسال شده')], default='submitted', max_length=15),
        ),
    ]
